---
galaxy_info:
  role_name: pyenv
  author: Thomas Kiss
  description: Install pyenv (+ pyenv-virtualenv) and the CPython build dependencies
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - noble
dependencies: []
