---
xsecurelock_repo: https://github.com/google/xsecurelock.git
xsecurelock_version: master
xsecurelock_src: "{{ ansible_env.HOME }}/.sources/xsecurelock"
xsecurelock_bin: /usr/local/bin/xsecurelock
xsecurelock_pam_service: common-auth

xsecurelock_build_packages:
  - build-essential
  - autoconf
  - automake
  - pkg-config
  - libpam0g-dev
  - libx11-dev
  - libxcomposite-dev
  - libxext-dev
  - libxfixes-dev
  - libxft-dev
  - libxmu-dev
  - libxrandr-dev
  - libxss-dev
