---
editor_nvim_bin: /usr/local/bin/nvim
editor_nvim_repo: https://github.com/neovim/neovim.git
editor_nvim_version: stable
editor_nvim_src: "{{ ansible_env.HOME }}/.sources/neovim"

editor_config_repo: git@github.com:thokis/kickstart.nvim.git
editor_config_version: master
editor_config_dir: "{{ ansible_env.HOME }}/.config/nvim"

editor_packages:
  - build-essential   # neovim build
  - ninja-build       # neovim build
  - gettext           # neovim build
  - cmake             # neovim build
  - unzip             # neovim build
  - curl              # neovim build
  - ripgrep           # telescope live grep
  - fd-find           # telescope file finding

editor_default_apps:
  - {mime: text/plain, app: nvim.desktop}
