---
galaxy_info:
  role_name: editor
  author: Thomas Kiss
  description: nvim as the default text editor/viewer on Ubuntu GNOME
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - noble
dependencies: []
