---
terminal_ghostty_bin: /usr/bin/ghostty

terminal_required_bins:
  - ghostty

terminal_install_packages:
  - python3-nautilus

terminal_remove_packages:
  - gnome-terminal
  - nautilus-extension-gnome-terminal
  - xterm

terminal_default_apps:
  - {mime: x-scheme-handler/terminal, app: com.mitchellh.ghostty.desktop}
  - {mime: application/x-terminal-emulator, app: com.mitchellh.ghostty.desktop}

terminal_keybinding_base: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings

terminal_keybindings:
  - {id: custom0, name: Terminal, command: ghostty, binding: <Super>Return}
  - {id: custom1, name: Terminal, command: ghostty -e tmux, binding: <Shift><Super>Return}
