#!/usr/bin/env bash
# Generate a gitignored .env with fresh OpenBao AppRole credentials for the
# provisioning run. Uses your SSH access to helios9 (where OpenBao runs) to read
# the role_id and mint a new secret_id — so you never copy secrets around by hand.
#
# Usage:  scripts/bootstrap-secrets-env.sh
# Then:   scripts/provision.sh [ansible-playbook args...]
set -euo pipefail

HELIOS9="${HELIOS9:-helios9}"                       # ssh host alias
ROLE="${ROLE:-ansible-provision}"                   # OpenBao AppRole name
BAO_PUBLIC="${BAO_PUBLIC:-https://bao.helios9.org}" # what the controller talks to
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

bao() { ssh "$HELIOS9" "docker exec -e BAO_ADDR=http://127.0.0.1:8200 openbao bao $*"; }

echo "Reading role_id and minting a fresh secret_id from $HELIOS9 ..." >&2
role_id="$(bao read -field=role_id "auth/approle/role/$ROLE/role-id")"
secret_id="$(bao write -f -field=secret_id "auth/approle/role/$ROLE/secret-id")"

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/bootstrap-secrets-env.sh on $(date -Is). DO NOT COMMIT.
# community.hashi_vault reads these automatically.
export ANSIBLE_HASHI_VAULT_ADDR='$BAO_PUBLIC'
export ANSIBLE_HASHI_VAULT_AUTH_METHOD='approle'
export ANSIBLE_HASHI_VAULT_ROLE_ID='$role_id'
export ANSIBLE_HASHI_VAULT_SECRET_ID='$secret_id'
EOF
chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE (0600). Run provisioning with: scripts/provision.sh" >&2
